---
apiVersion: v1
kind: ConfigMap
metadata:
  name: avro-producer-config
data:
  producer.properties: |
    # Required connection configs for Kafka producer, consumer, and admin
    bootstrap.servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092
    # Required for correctness in Apache Kafka clients prior to 2.6
    client.dns.lookup=use_all_dns_ips
    # Best practice for higher availability in Apache Kafka clients prior to 3.0
    session.timeout.ms=45000
    # Best practice for Kafka producer to prevent data loss
    acks=all
    # Schema Registry connection configurations
    schema.registry.url=https://psrc-5j7x8.us-central1.gcp.confluent.cloud
    # Other configurations
    retries=0
  user.configuration: |
    topicName: numagen-avro
    schemaType: avro
    schemaSubject: numagen-avro-value
    schemaVersion: 1
