apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
type: Opaque
data:
  kafka.properties: "c2VjdXJpdHkucHJvdG9jb2w9U0FTTF9TU0wKc2FzbC5qYWFzLmNvbmZpZz1vcmcuYXBhY2hlLmthZmthLmNvbW1vbi5zZWN1cml0eS5wbGFpbi5QbGFpbkxvZ2luTW9kdWxlIHJlcXVpcmVkIHVzZXJuYW1lPSdTUjdSTTY3SUtCVlhGWlpQJyBwYXNzd29yZD0nSlFYVHgrcjJDZFllTDEzaWZGVzY2NVlEdmZrTWIwaXJoRDVVcWZqeWNJRHJxRXlLSEpTYmFoSDcrbCt5NnAveSc7CnNhc2wubWVjaGFuaXNtPVBMQUlOCmJhc2ljLmF1dGguY3JlZGVudGlhbHMuc291cmNlPVVTRVJfSU5GTwpiYXNpYy5hdXRoLnVzZXIuaW5mbz1UTkRNSFBFS1NTQ1FNNDVROjUvWDR1MzQxZlVsTDNsN3AyMkluVm9xekg3M2FzaXNQZjV5ck9YeWlmMncxQ24wUWlQV0FoWnp2T2E3OXFCK00="