apiVersion: v1
kind: Secret
metadata:
  name: kafka-credentials
type: Opaque
data:
  kafka.credential.properties: "c2FzbC5qYWFzLmNvbmZpZz1bcGxhY2Vob2xkZXJdCmJhc2ljLmF1dGgudXNlci5pbmZvPVtwbGFjZWhvbGRlcl0="