apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: test-pipeline-producer
spec:
  vertices:
    - name: in
      scale:
        min: 1
      source:
        generator:
          rpu: 1
          duration: 1s
    - name: cat
      scale:
        min: 1
      udf:
        builtin:
          name: cat
    - name: sink
      volumes:
        - name: kafka-config-volume
          configMap:
            name: kafka-config
            items:
              - key: user.configuration
                path: user.configuration.yaml
              - key: producer.properties
                path: producer.properties
              - key: schema.registry.properties
                path: schema.registry.properties
      scale:
        min: 1
        max: 2
      limits:
        readBatchSize: 50
      sink:
        udsink:
          container:
            image: quay.io/numaio/numaflow-java/kafka-java:v0.2.0
            args: [ "--spring.config.location=file:/conf/user.configuration.yaml", "--producer.properties.path=/conf/producer.properties", "--schema.registry.properties.path=/conf/schema.registry.properties" ]
            imagePullPolicy: Always
            volumeMounts:
              - name: kafka-config-volume
                mountPath: /conf
  edges:
    - from: in
      to: cat
    - from: cat
      to: sink