apiVersion: numaflow.numaproj.io/v1alpha1
kind: Pipeline
metadata:
  name: test-pipeline-consumer
spec:
  vertices:
    - name: in
      volumes:
        - name: kafka-config-volume
          configMap:
            name: kafka-config
            items:
              - key: user.configuration
                path: user.configuration.yaml
              - key: consumer.properties
                path: consumer.properties
      scale:
        min: 1
        max: 2
      limits:
        readBatchSize: 500
      source:
        udsource:
          container:
            image: quay.io/numaio/numaflow-java/kafka-java:v0.2.0
            args: [ "--spring.config.location=file:/conf/user.configuration.yaml", "--consumer.properties.path=/conf/consumer.properties" ]
            imagePullPolicy: Always
            volumeMounts:
              - name: kafka-config-volume
                mountPath: /conf
    - name: cat
      scale:
        min: 1
      udf:
        builtin:
          name: cat
    - name: sink
      scale:
        min: 1
      sink:
        log:
          { }
  edges:
    - from: in
      to: cat
    - from: cat
      to: sink